using Microsoft.EntityFrameworkCore;
using NovaChat.Server.Data;
using NovaChat.Server.Entities;

namespace NovaChat.Server.Services;

public class ChatService
{
    private static readonly SemaphoreSlim CreateChatLock = new(1, 1);
    private readonly AppDbContext _context;
    public ChatService(AppDbContext context) => _context = context;
    public Task<bool> UserExistsAsync(long userId) => _context.Users.AsNoTracking().AnyAsync(u => u.Id == userId);
    public Task<User?> GetUserByUsernameAsync(string username) => _context.Users.FirstOrDefaultAsync(u => u.Username == username.Trim().ToLowerInvariant());
    public Task SaveChangesAsync() => _context.SaveChangesAsync();

    public async Task<Chat?> CreatePrivateChatAsync(long currentUserId, long otherUserId)
    {
        if (currentUserId <= 0 || otherUserId <= 0 || currentUserId == otherUserId) return null; if (!await UserExistsAsync(currentUserId) || !await UserExistsAsync(otherUserId)) return null;
        await CreateChatLock.WaitAsync();
        try
        {
            var existing = await _context.Chats.Include(c => c.User1).Include(c => c.User2).Where(c => c.Type == ChatType.Private && ((c.User1Id == currentUserId && c.User2Id == otherUserId) || (c.User1Id == otherUserId && c.User2Id == currentUserId))).OrderBy(c => c.Id).ToListAsync();
            if (existing.Count > 0) { var chat = existing[0]; if (existing.Count > 1) { _context.Chats.RemoveRange(existing.Skip(1)); await _context.SaveChangesAsync(); } await EnsurePrivateMembersAsync(chat, currentUserId, otherUserId); return chat; }
            var newChat = new Chat { Type = ChatType.Private, Name = string.Empty, CreatedByUserId = currentUserId, User1Id = currentUserId, User2Id = otherUserId }; _context.Chats.Add(newChat); await _context.SaveChangesAsync(); await EnsurePrivateMembersAsync(newChat, currentUserId, otherUserId); await _context.Entry(newChat).Reference(c => c.User1).LoadAsync(); await _context.Entry(newChat).Reference(c => c.User2).LoadAsync(); return newChat;
        }
        finally { CreateChatLock.Release(); }
    }
    private async Task EnsurePrivateMembersAsync(Chat chat, long ownerId, long otherId) { foreach (var id in new[] { ownerId, otherId }) if (!await _context.ChatMembers.AnyAsync(m => m.ChatId == chat.Id && m.UserId == id)) _context.ChatMembers.Add(new ChatMember { ChatId = chat.Id, UserId = id, Role = id == ownerId ? ChatMemberRole.Owner : ChatMemberRole.Member, JoinedAt = chat.CreatedAt }); await _context.SaveChangesAsync(); }
    public async Task<Chat?> CreateGroupChatAsync(long creatorId, string name, IEnumerable<string> usernames)
    {
        name = name.Trim(); if (string.IsNullOrWhiteSpace(name) || name.Length > 128) return null; var normalized = usernames.Where(x => !string.IsNullOrWhiteSpace(x)).Select(x => x.Trim().ToLowerInvariant()).Distinct().ToList(); var users = await _context.Users.Where(u => normalized.Contains(u.Username)).ToListAsync(); if (users.Count != normalized.Count) return null; users.RemoveAll(u => u.Id == creatorId); var creator = await _context.Users.FirstOrDefaultAsync(u => u.Id == creatorId); if (creator == null) return null; var chat = new Chat { Type = ChatType.Group, Name = name, CreatedByUserId = creatorId, User1Id = null, User2Id = null }; _context.Chats.Add(chat); await _context.SaveChangesAsync(); _context.ChatMembers.Add(new ChatMember { ChatId = chat.Id, UserId = creatorId, Role = ChatMemberRole.Owner }); foreach (var user in users) _context.ChatMembers.Add(new ChatMember { ChatId = chat.Id, UserId = user.Id, Role = ChatMemberRole.Member }); await _context.SaveChangesAsync(); return await GetChatByIdAsync(chat.Id);
    }
    public async Task<List<Chat>> GetUserChatsAsync(long userId) { var chats = await _context.Chats.AsNoTracking().Include(c => c.User1).Include(c => c.User2).Where(c => c.Members.Any(m => m.UserId == userId) || (c.Type == ChatType.Private && (c.User1Id == userId || c.User2Id == userId))).OrderByDescending(c => c.CreatedAt).ThenByDescending(c => c.Id).ToListAsync(); foreach (var chat in chats) { var last = await GetLastMessageAsync(chat.Id); chat.Messages = last == null ? [] : [last]; } return chats.OrderByDescending(c => c.Messages.FirstOrDefault()?.SentAt ?? c.CreatedAt).ThenByDescending(c => c.Id).ToList(); }
    public async Task<List<Chat>> GetAllChatsAsync() { var chats = await _context.Chats.AsNoTracking().Include(c => c.User1).Include(c => c.User2).OrderByDescending(c => c.CreatedAt).ThenByDescending(c => c.Id).ToListAsync(); foreach (var chat in chats) { var last = await GetLastMessageAsync(chat.Id); chat.Messages = last == null ? [] : [last]; } return chats.OrderByDescending(c => c.Messages.FirstOrDefault()?.SentAt ?? c.CreatedAt).ThenByDescending(c => c.Id).ToList(); }
    public Task<Chat?> GetChatByIdAsync(int chatId) => _context.Chats.Include(c => c.User1).Include(c => c.User2).Include(c => c.Members).ThenInclude(m => m.User).FirstOrDefaultAsync(c => c.Id == chatId);
    public Task<bool> CanAccessChatAsync(int chatId, long userId) => _context.Chats.AnyAsync(c => c.Id == chatId && (c.Members.Any(m => m.UserId == userId) || (c.Type == ChatType.Private && (c.User1Id == userId || c.User2Id == userId))));
    public async Task<Message?> SendMessageAsync(int chatId, long senderId, string content) { if (string.IsNullOrWhiteSpace(content) || !await CanAccessChatAsync(chatId, senderId)) return null; var chat = await _context.Chats.FirstOrDefaultAsync(c => c.Id == chatId); if (chat == null) return null; var message = new Message { ChatId = chatId, SenderId = senderId, Content = content.Trim() }; _context.Messages.Add(message); await _context.SaveChangesAsync(); await _context.Entry(message).Reference(m => m.Sender).LoadAsync(); return message; }
    public async Task<List<Message>> GetMessagesAsync(int chatId, int? beforeMessageId = null, int pageSize = 50) { pageSize = Math.Clamp(pageSize, 1, 100); var query = _context.Messages.AsNoTracking().Include(m => m.Sender).Where(m => m.ChatId == chatId && !m.DeletedForEveryone); if (beforeMessageId.HasValue) { var before = await _context.Messages.AsNoTracking().FirstOrDefaultAsync(m => m.Id == beforeMessageId.Value && m.ChatId == chatId && !m.DeletedForEveryone); if (before != null) query = query.Where(m => m.SentAt < before.SentAt || (m.SentAt == before.SentAt && m.Id < before.Id)); } var messages = await query.OrderByDescending(m => m.SentAt).ThenByDescending(m => m.Id).Take(pageSize + 1).ToListAsync(); if (messages.Count > pageSize) messages.RemoveAt(messages.Count - 1); return messages.OrderBy(m => m.SentAt).ThenBy(m => m.Id).ToList(); }
    public async Task<bool> HasOlderMessagesAsync(int chatId, int firstMessageId) { var first = await _context.Messages.AsNoTracking().FirstOrDefaultAsync(m => m.Id == firstMessageId && m.ChatId == chatId && !m.DeletedForEveryone); return first != null && await _context.Messages.AsNoTracking().AnyAsync(m => m.ChatId == chatId && !m.DeletedForEveryone && (m.SentAt < first.SentAt || (m.SentAt == first.SentAt && m.Id < first.Id))); }
    public Task<Message?> GetLastMessageAsync(int chatId) => _context.Messages.AsNoTracking().Include(m => m.Sender).Where(m => m.ChatId == chatId && !m.DeletedForEveryone).OrderByDescending(m => m.SentAt).ThenByDescending(m => m.Id).FirstOrDefaultAsync();
    public Task<Message?> GetMessageByIdAsync(int messageId) => _context.Messages.AsNoTracking().FirstOrDefaultAsync(m => m.Id == messageId);
    public async Task<List<ChatMember>> GetMembersAsync(int chatId) => await _context.ChatMembers.AsNoTracking().Include(m => m.User).Where(m => m.ChatId == chatId).OrderByDescending(m => m.Role).ThenBy(m => m.JoinedAt).ToListAsync();
    public async Task<ChatMember?> GetMemberAsync(int chatId, long userId) => await _context.ChatMembers.FirstOrDefaultAsync(m => m.ChatId == chatId && m.UserId == userId);
    public async Task<bool> AddMemberAsync(int chatId, long actorId, long userId) { var chat = await _context.Chats.FirstOrDefaultAsync(c => c.Id == chatId && c.Type == ChatType.Group); if (chat == null) return false; var actor = await GetMemberAsync(chatId, actorId); if (actor == null || actor.Role == ChatMemberRole.Member) return false; if (await GetMemberAsync(chatId, userId) != null) return true; if (!await UserExistsAsync(userId)) return false; _context.ChatMembers.Add(new ChatMember { ChatId = chatId, UserId = userId, Role = ChatMemberRole.Member }); await _context.SaveChangesAsync(); return true; }
    public async Task<bool> RemoveMemberAsync(int chatId, long actorId, long userId) { var chat = await _context.Chats.FirstOrDefaultAsync(c => c.Id == chatId && c.Type == ChatType.Group); if (chat == null) return false; var actor = await GetMemberAsync(chatId, actorId); var target = await GetMemberAsync(chatId, userId); if (actor == null || target == null || actor.Role == ChatMemberRole.Member || target.Role == ChatMemberRole.Owner) return false; if (actor.Role == ChatMemberRole.Admin && target.Role != ChatMemberRole.Member) return false; _context.ChatMembers.Remove(target); await _context.SaveChangesAsync(); return true; }
    public async Task<bool> LeaveGroupAsync(int chatId, long userId) { var member = await GetMemberAsync(chatId, userId); if (member == null || member.Role == ChatMemberRole.Owner) return false; _context.ChatMembers.Remove(member); await _context.SaveChangesAsync(); return true; }
    public async Task<bool> RenameGroupAsync(int chatId, long actorId, string name) { name = name.Trim(); if (string.IsNullOrWhiteSpace(name) || name.Length > 128) return false; var chat = await _context.Chats.FirstOrDefaultAsync(c => c.Id == chatId && c.Type == ChatType.Group); if (chat == null) return false; var actor = await GetMemberAsync(chatId, actorId); if (actor == null || actor.Role == ChatMemberRole.Member) return false; chat.Name = name; await _context.SaveChangesAsync(); return true; }
    public async Task<bool> DeleteChatAsync(int chatId) { var chat = await _context.Chats.FirstOrDefaultAsync(c => c.Id == chatId); if (chat == null) return false; _context.Chats.Remove(chat); await _context.SaveChangesAsync(); return true; }
    public async Task<bool> DeleteMessageAsync(int messageId) { var message = await _context.Messages.FirstOrDefaultAsync(m => m.Id == messageId); if (message == null) return false; _context.Messages.Remove(message); await _context.SaveChangesAsync(); return true; }
    public Task<int?> GetMessageChatIdAsync(int messageId) => _context.Messages.Where(m => m.Id == messageId).Select(m => (int?)m.ChatId).FirstOrDefaultAsync();
}
