using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NovaChat.Server.Migrations;

public partial class AddContacts : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        // The Contacts table may already exist in databases created before
        // this migration was registered in __EFMigrationsHistory.
        // Keep this migration idempotent so existing data is preserved.
        migrationBuilder.Sql("""
            CREATE TABLE IF NOT EXISTS "Contacts" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "OwnerUserId" text NOT NULL,
                "ContactUserId" text NOT NULL,
                "CreatedAt" timestamp with time zone NOT NULL,
                CONSTRAINT "PK_Contacts" PRIMARY KEY ("Id"),
                CONSTRAINT "FK_Contacts_Users_ContactUserId" FOREIGN KEY ("ContactUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
                CONSTRAINT "FK_Contacts_Users_OwnerUserId" FOREIGN KEY ("OwnerUserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
            );
            """);

        migrationBuilder.Sql("""
            CREATE INDEX IF NOT EXISTS "IX_Contacts_ContactUserId"
            ON "Contacts" ("ContactUserId");
            """);

        migrationBuilder.Sql("""
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_Contacts_OwnerUserId_ContactUserId"
            ON "Contacts" ("OwnerUserId", "ContactUserId");
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("DROP TABLE IF EXISTS \"Contacts\";");
    }
}
