// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NovaChat.Server.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NovaChat.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11").HasAnnotation("Relational:MaxIdentifierLength", 63);
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NovaChat.Server.Entities.Chat", b => { b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer"); NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id")); b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone"); b.Property<string>("User1Id").IsRequired().HasColumnType("text"); b.Property<string>("User2Id").IsRequired().HasColumnType("text"); b.HasKey("Id"); b.HasIndex("User1Id"); b.HasIndex("User2Id"); b.ToTable("Chats"); });
            modelBuilder.Entity("NovaChat.Server.Entities.Contact", b => { b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer"); NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id")); b.Property<string>("ContactUserId").IsRequired().HasColumnType("text"); b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone"); b.Property<string>("OwnerUserId").IsRequired().HasColumnType("text"); b.HasKey("Id"); b.HasIndex("ContactUserId"); b.HasIndex("OwnerUserId", "ContactUserId").IsUnique(); b.ToTable("Contacts"); });
            modelBuilder.Entity("NovaChat.Server.Entities.Message", b => { b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer"); NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id")); b.Property<int>("ChatId").HasColumnType("integer"); b.Property<string>("Content").IsRequired().HasColumnType("text"); b.Property<bool>("DeletedForEveryone").HasColumnType("boolean"); b.Property<string>("DeletedForUserIds").IsRequired().HasColumnType("text"); b.Property<string>("SenderId").IsRequired().HasColumnType("text"); b.Property<DateTime>("SentAt").HasColumnType("timestamp with time zone"); b.HasKey("Id"); b.HasIndex("ChatId"); b.HasIndex("SenderId"); b.ToTable("Messages"); });
            modelBuilder.Entity("NovaChat.Server.Entities.User", b => { b.Property<string>("Id").HasColumnType("text"); b.Property<string>("AvatarUrl").HasColumnType("text"); b.Property<string>("Bio").IsRequired().HasColumnType("text"); b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone"); b.Property<string>("DisplayName").IsRequired().HasColumnType("text"); b.Property<string>("Email").IsRequired().HasColumnType("text"); b.Property<DateTime?>("LastSeenAt").HasColumnType("timestamp with time zone"); b.Property<string>("PasswordHash").IsRequired().HasColumnType("text"); b.HasKey("Id"); b.ToTable("Users"); });

            modelBuilder.Entity("NovaChat.Server.Entities.Chat", b => { b.HasOne("NovaChat.Server.Entities.User", "User1").WithMany().HasForeignKey("User1Id").OnDelete(DeleteBehavior.Restrict).IsRequired(); b.HasOne("NovaChat.Server.Entities.User", "User2").WithMany().HasForeignKey("User2Id").OnDelete(DeleteBehavior.Restrict).IsRequired(); b.Navigation("User1"); b.Navigation("User2"); });
            modelBuilder.Entity("NovaChat.Server.Entities.Contact", b => { b.HasOne("NovaChat.Server.Entities.User", "ContactUser").WithMany().HasForeignKey("ContactUserId").OnDelete(DeleteBehavior.Restrict).IsRequired(); b.HasOne("NovaChat.Server.Entities.User", "OwnerUser").WithMany().HasForeignKey("OwnerUserId").OnDelete(DeleteBehavior.Cascade).IsRequired(); b.Navigation("ContactUser"); b.Navigation("OwnerUser"); });
            modelBuilder.Entity("NovaChat.Server.Entities.Message", b => { b.HasOne("NovaChat.Server.Entities.Chat", "Chat").WithMany("Messages").HasForeignKey("ChatId").OnDelete(DeleteBehavior.Cascade).IsRequired(); b.HasOne("NovaChat.Server.Entities.User", "Sender").WithMany().HasForeignKey("SenderId").OnDelete(DeleteBehavior.Restrict).IsRequired(); b.Navigation("Chat"); b.Navigation("Sender"); });

            modelBuilder.Entity("NovaChat.Server.Entities.Chat", b => b.Navigation("Messages"));
#pragma warning restore 612, 618
        }
    }
}