using System.ComponentModel.DataAnnotations.Schema;

namespace NovaChat.Server.Entities;

public class User
{
    // IDs are generated by NovaChat in UserService, not by MariaDB.
    // This is intentionally disabled for database-generated values because the
    // existing MariaDB schema stores this key as a string-compatible value.
    [DatabaseGenerated(DatabaseGeneratedOption.None)]
    public long Id { get; set; }

    public string Username { get; set; } = string.Empty;
    public string DisplayName { get; set; } = string.Empty;
    public string Email { get; set; } = string.Empty;
    public string? PhoneNumber { get; set; }
    public string PasswordHash { get; set; } = string.Empty;
    public string Bio { get; set; } = string.Empty;
    public string? AvatarUrl { get; set; }
    public DateTime? LastSeenAt { get; set; }
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
}
